### ISSUE TITLE
为啥登上自己退出了

### ISSUE THREAD

**Issue by phpcs** [shanghai-edu/multissh#13]
![image](https://user-images.githubusercontent.com/6924640/91170603-b2e17d00-e70b-11ea-9415-ddf1d0a211cf.png)
输入命令后能看到阿里云欢迎信息, 然后又自动退出了

**Comment by freedomkk-qfeng** [comment]
会在命令后自动加一个 exit
不然就hang在里面了呀，这个不是持久的 ssh 交互工具，是用来跑预制好的命令任务的
