### ISSUE TITLE
希望能够获取执行命令失败的报错信息，而不仅仅返回错误代码

### ISSUE THREAD

**Issue by feehoo** [shanghai-edu/multissh#15]
现在执行命令失败只能返回错误代码，无法看到失败的提示信息，希望能够获取执行命令失败的报错信息，而不仅仅返回错误代码

**Comment by freedomkk-qfeng** [comment]
超时了会没有具体信息，如果时任务执行失败的话应该会打印失败时的会话输出的。
可以尝试手动的给一个能让任务退出的命令，multissh 会自动的添加 exit 到命令的末尾，对于不能通过 exit 退出的系统或者交换机而言，可以在命令列表最后加一个能退出的指令。
