### ISSUE TITLE
multissh不适用已经添加了公钥的机器

### ISSUE THREAD

**Issue by zhangyc0816** [shanghai-edu/multissh#2]
你好，multissh不适用已经添加了公钥的机器。公钥免密登录的场景会更多。可否不加 -p或者 -k 默认走公钥登录呢？

**Comment by freedomkk-qfeng** [comment]
现在使用 ssh key 认证需要在 multissh 的参数或配置中指定 公钥文件。
后续会尝试增加直接读服务器上的 authorized_keys 来完成自动适配

**Comment by zhangyc0816** [comment]
好的。感谢。
