### ISSUE TITLE
Bug: not enough arguments in call to `connect`

### ISSUE THREAD

**Issue by TieWay59** [shanghai-edu/multissh#20]
https://github.com/shanghai-edu/multissh/blob/87e207932fcab1f25d843752b25057d3272519f5/funcs/ssh_test.go#L56-L58

> :warning:  not enough arguments in call to connect
	have (string, string, string, string, number, []string)
	want (string, string, string, string, int, []string, []string)

在上述代码中 `connect` 函数没有足够的函数参数。

**Comment by freedomkk-qfeng** [comment]
测试用例没及时更新，这里应该还有一个 keyExchangeList 的入参，用于协商 ssh 握手时的 
测试用例给 nil 即可，当入参为空数组时，会默认给
config.KeyExchanges = []string{"diffie-hellman-group-exchange-sha1", "diffie-hellman-group1-sha1", "diffie-hellman-group-exchange-sha256"}

这里可以更新下测试用例，包括被注释掉的 Test_SSH（这部分是 session.shell 的测试），并找个 linux 等可以 ssh 测试的终端跑一下测试。
