### ISSUE TITLE
“SSH run timeout：30 second.” that‘s why？

### ISSUE THREAD

**Issue by halleyshx** [shanghai-edu/multissh#9]
That's why retrun “SSH run timeout：30 second.”?
```
./multissh -cmds "cd /home;ls;exit" -hosts "192.168.182.65" -u root -p clouds                          
2019/06/27 20:32:56 Multissh start
2019/06/27 20:33:26 Multissh finished. Process time 30.000306562s. Number of active ip is 1
host:  192.168.182.65
========= Result =========
SSH run timeout：30 second.
```
ping is ok.
```
ping 192.168.182.65
PING 192.168.182.65 (192.168.182.65) 56(84) bytes of data.
64 bytes from 192.168.182.65: icmp_seq=1 ttl=64 time=0.111 ms
64 bytes from 192.168.182.65: icmp_seq=2 ttl=64 time=0.127 ms
64 bytes from 192.168.182.65: icmp_seq=3 ttl=64 time=0.083 ms
```
ssh root@192.168.182.65 is ok.
what's wrong with me And what can I do?

**Comment by freedomkk-qfeng** [comment]
```
# ./multissh -cmds "cd /home;ls;exit" -hosts "192.168.88.101" -u root -p password                      
2019/07/08 00:21:55 Multissh start
2019/07/08 00:21:56 Multissh finished. Process time 548.964287ms. Number of active ip is 1
host:  192.168.88.101
========= Result =========
Last login: Sun Jul  7 00:44:48 2019 from 172.20.152.65
[root@test ~]# [root@test home]# logs  webapps
[root@test home]# logout
```
I test thess cmds on centos7 and works ok. Please provide your OS and version.
And on linux, your can use `-l` for linux mode, then you can combine cmds with `&`, like this.
```
# ./multissh -l -cmds "cd /home&&ls&&exit" -hosts "192.168.88.101" -u root -p password    
2019/07/08 00:24:20 Multissh start
2019/07/08 00:24:20 Multissh finished. Process time 214.614387ms. Number of active ip is 1
host:  192.168.88.101
========= Result =========
logs  webapps

```

**Comment by halleyshx** [comment]
> ```
> # ./multissh -cmds "cd /home;ls;exit" -hosts "192.168.88.101" -u root -p password                      
> 2019/07/08 00:21:55 Multissh start
> 2019/07/08 00:21:56 Multissh finished. Process time 548.964287ms. Number of active ip is 1
> host:  192.168.88.101
> ========= Result =========
> Last login: Sun Jul  7 00:44:48 2019 from 172.20.152.65
> [root@test ~]# [root@test home]# logs  webapps
> [root@test home]# logout
> ```
> 
> I test thess cmds on centos7 and works ok. Please provide your OS and version.
> And on linux, your can use `-l` for linux mode, then you can combine cmds with `&`, like this.
> 
> ```
> # ./multissh -l -cmds "cd /home&&ls&&exit" -hosts "192.168.88.101" -u root -p password    
> 2019/07/08 00:24:20 Multissh start
> 2019/07/08 00:24:20 Multissh finished. Process time 214.614387ms. Number of active ip is 1
> host:  192.168.88.101
> ========= Result =========
> logs  webapps
> ```

When I add “-l” for linux mode，It worked！ Thanks！
